Add section on clock priority levels in SE (#29)
modelica/fmi-guides pull request #34
Opened 2022-04-15 09:46 UTC by pmai

Closes #29.

2022-04-15 09:47 UTC, pmai commented
Note that I have copied over the remaining non-normative sections in 5.1.1, too, since they seem related in order to understand the full role of priorities. @MBlesken please check if it would make sense to also remove them in the standard, or to leave this information duplicated, which would be fine be me.

2022-04-17 11:25 UTC, andreas-junghanns approved these changes

2022-04-19 05:59 UTC, MBlesken requested changes
Minor remarks

2022-04-19 05:59 UTC, MBlesken commented on fmi-guide/8___scheduled-execution.adoc
> +In scheduled execution clocks can be assigned priority information through the `priority` attribute on the clock variable.
*must* be assigned

2022-04-19 05:59 UTC, MBlesken commented on fmi-guide/8___scheduled-execution.adoc
> +A clock's priority information is required to support the scheduled execution of several model partitions, especially in a preemptive scheduling regime.
"*especially* in a preemptive scheduling regime." is confusing: SE doesn't work without priorities. Preemption can be regarded as just another feature.

2022-04-19 06:02 UTC, MBlesken commented
> Note that I have copied over the remaining non-normative sections in 5.1.1, too, since they seem related in order to understand the full role of priorities. @MBlesken please check if it would make sense to also remove them in the standard, or to leave this information duplicated, which would be fine be me.


@pmai Can we look at it together in a design meeting? I'm not sure where to get orientation from to decide on the level that makes sense to leave and to move....

2022-04-26 10:30 UTC, merged