Add section on preemption handling for SE (#30)
modelica/fmi-guides pull request #35
Opened 2022-04-15 10:08 UTC by pmai

Closes #30.

2022-04-15 10:10 UTC, pmai commented
If we do include this in the IG, I think most of the non-normative stuff in 5.1 could be removed. The one exception I would make is to leave in the note on locking being expensive, and hence segregating variables to model partitions and related advice should be included. I'll make a proposal.

2022-04-17 11:23 UTC, andreas-junghanns commented on fmi-guide/8___scheduled-execution.adoc
> +* _An output variable is changed by two different model partitions:_ +
Formatting with _ intentional?

2022-04-17 11:23 UTC, andreas-junghanns commented on fmi-guide/8___scheduled-execution.adoc
> +* _An input variable is used by two different model partitions:_ +
Formatting with _ intentional?

2022-04-17 11:24 UTC, andreas-junghanns approved these changes
Except for the two formatting remarks (handle at your own discretion), approved.

2022-04-19 05:59 UTC, MBlesken requested changes
Minor remarks

2022-04-19 05:59 UTC, MBlesken commented on fmi-guide/8___scheduled-execution.adoc
> +In such cases no locks may be necessary.
are necessary

2022-04-19 07:49 UTC, pmai commented on fmi-guide/8___scheduled-execution.adoc
> +In such cases no locks may be necessary.
That is however not generally true, which is why I changed it to might: Preemption can pose problems (like timing effects, but also other global state) that are independent of the data protection of FMU internal data. An FMU partition therefore can need to avoid preemption even if it is the only one running of that FMU (consider e.g. HW access with timing constraints). OTOH, BTW, an FMU could use lockless approaches to guard its internal state.

In order not to get bogged down into a course on pre-emption, re-entrance, locking algorithms and HW interfaces, I've changed the wording so that we at least don't lie...

2022-04-19 08:26 UTC, pmai commented on fmi-guide/8___scheduled-execution.adoc
> +In such cases no locks may be necessary.
BTW, I seem to have misremembered, this wording was already exactly in this way, with may, in the original text from the standard. So probably the original author had the same thing in mind (I only changed other text to match that)...

2022-04-26 10:12 UTC, merged