Add section on which functions to implement
modelica/fmi-guides pull request #74
Opened 2023-05-16 14:51 UTC by pmai

2024-06-18 17:21 UTC, Maplesoft-fmigroup commented on fmi-guide/3___packaging.adoc
> +The situation for optional features is unclear.
Maybe it's better to say "The requirement for optional..."

2024-06-18 17:26 UTC, Maplesoft-fmigroup commented on fmi-guide/3___packaging.adoc
> +Similarly it is recommended for exporters always generate all functions specified in the relevant standards.
Change either to "it is recommended that exporters" or "for exporters to always generate" (the first one is more grammatically correct).

2024-06-18 17:27 UTC, Maplesoft-fmigroup commented on fmi-guide/3___packaging.adoc
> +Unsupported feature and interface type functions should be implemented to return an appropriate error code (e.g. `fmi3Error`) when called, after logging the reason for the error.
Should the logging be done only if logging is turned on?

2024-06-18 17:31 UTC, Maplesoft-fmigroup requested changes
Couple of small additional comments have been added.

2024-06-18 17:31 UTC, Maplesoft-fmigroup commented on fmi-guide/3___packaging.adoc
> +In the initial 3.0 release, this specification was ambiguous and broken: While the intent always was for all functions to be present, it could be read as only requiring the functions of those interfa
Perhaps "ambiguous" is enough (without the "broken" part)

2025-01-28 15:50 UTC, chrbertsch approved these changes

2025-01-28 15:50 UTC, chrbertsch commented on fmi-guide/3___packaging.adoc
> +In the initial 3.0 release, this specification was ambiguous and broken: While the intent always was for all functions to be present, it could be read as only requiring the functions of those interfa
```suggestion
In the initial 3.0 release, this specification was ambiguous: While the intent always was for all functions to be present, it could be read as only requiring the functions of those interface types the FMU supports having to be present.
```

2025-01-28 15:50 UTC, chrbertsch commented on fmi-guide/3___packaging.adoc
> +The situation for optional features is unclear.
```suggestion
The requirements for optional features are unclear.
```

2025-01-28 15:50 UTC, chrbertsch commented on fmi-guide/3___packaging.adoc
> +Similarly it is recommended for exporters always generate all functions specified in the relevant standards.
```suggestion
Similarly it is recommended that exporters always generate all functions specified in the relevant standards.
```

2025-01-28 15:50 UTC, chrbertsch commented on fmi-guide/3___packaging.adoc
> +Unsupported feature and interface type functions should be implemented to return an appropriate error code (e.g. `fmi3Error`) when called, after logging the reason for the error.
The rules of the standard apply ... . The standard says "should". Section 2.2.4. When a resource is missing, it is required.

2025-01-28 15:52 UTC, merged